# Generated by Django 5.2.4 on 2025-08-05 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Лидер'), ('officer', 'Офицер'), ('member', 'Участник'), ('recruit', 'Новичок')], default='recruit', max_length=20, verbose_name='Роль')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('game_nickname', models.CharField(blank=True, max_length=100, verbose_name='Игровой никнейм')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Член клана',
                'verbose_name_plural': 'Члены клана',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Содержание')),
                ('category', models.CharField(choices=[('game', 'Игра'), ('clan', 'Клан'), ('events', 'События'), ('updates', 'Обновления')], default='clan', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
