# Generated by Django 5.2.4 on 2025-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
        migrations.AddField(
            model_name='clanmember',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний раз онлайн'),
        ),
    ]
