# Generated by Django 5.2.4 on 2025-08-05 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clanmember_is_approved_clanmember_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('software', 'Программы'), ('mods', 'Моды'), ('guides', 'Гайды'), ('tools', 'Инструменты'), ('patches', 'Патчи'), ('other', 'Другое')], default='software', max_length=20, verbose_name='Категория')),
                ('download_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на загрузку')),
                ('file', models.FileField(blank=True, null=True, upload_to='useful_materials/', verbose_name='Файл для загрузки')),
                ('installation_guide', models.TextField(blank=True, null=True, verbose_name='Инструкция по установке')),
                ('image', models.ImageField(blank=True, null=True, upload_to='useful_materials/', verbose_name='Изображение')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Количество загрузок')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Полезный материал',
                'verbose_name_plural': 'Полезные материалы',
                'ordering': ['-created_at'],
            },
        ),
    ]
