# Generated by Django 4.1.7 on 2025-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_usefulmaterial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usefulmaterial",
            name="category",
            field=models.CharField(
                choices=[
                    ("software", "Софт"),
                    ("builder", "Билдер"),
                    ("auction", "Аукционный дом"),
                    ("mods", "Моды"),
                    ("guides", "Гайды"),
                    ("patches", "Патчи"),
                    ("other", "Другое"),
                ],
                default="software",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
